id: linkiubio
name: Linkiu Bio
environments:
  production:
    build:
      - 'composer install --no-dev --optimize-autoloader'
      - 'npm ci'
      - 'npm run build'
      - 'php artisan config:cache'
      - 'php artisan route:cache'
      - 'php artisan view:cache'
    deploy:
  - 'php artisan migrate --force'
  - 'php artisan migrate:images-to-storage'
  - 'php artisan config:clear'
  - 'php artisan cache:clear'
  - 'rm -rf /var/www/html/public/storage || true'
  - 'php artisan storage:link --force'
  - 'php artisan post-deploy:fix-storage'
  - 'ls -la /var/www/html/public/storage || echo "storage link missing"'
  - 'sleep 3'
  - 'php artisan post-deploy:fix-storage'
  - 'ls -la /var/www/html/public/ | grep storage || echo "final check failed"'
    variables:
      - APP_ENV=production
      - APP_DEBUG=false