id: linkiubio
name: Linkiu Bio
environments:
  production:
    build:
      - 'composer install --no-dev --optimize-autoloader'
      - 'npm ci'
      - 'npm run build'
      - 'php artisan config:cache'
      - 'php artisan route:cache'
      - 'php artisan view:cache'
    deploy:
      - 'php artisan migrate --force'
    variables:
      - APP_ENV=production
      - APP_DEBUG=false